import { DocSectionHeader } from "@/components/docs/doc-section-header";
import { CodeBlock } from "@/components/code-block";

const cssTokensCode = `@import "tailwindcss";

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-border: var(--border);
  --radius-lg: var(--radius);
}

:root {
  color-scheme: light;
}

.dark {
  color-scheme: dark;
}`;

export function ThemingTokensSection() {
  return (
    <div class="space-y-4">
      <DocSectionHeader
        title="CSS Tokens Reference"
        description="Standard CSS variables generated by nikala init in your main index.css / app.css."
      />
      <CodeBlock code={cssTokensCode} lang="css" />
    </div>
  );
}