import pc from "picocolors";
import type { DiffLine } from "./compare-lines.js";

/**
 * Formats and prints color-coded line differences to the terminal using picocolors.
 *
 * @param diffs - Array of diff line entries generated by compareLines
 * @returns Boolean indicating whether any differences were detected
 */
export function printFormattedDiff(diffs: DiffLine[]): boolean {
  const hasChanges = diffs.some((d) => d.type !== "same");

  if (!hasChanges) {
    return false;
  }

  console.log("");
  for (const entry of diffs) {
    if (entry.type === "add") {
      console.log(pc.green(`+ ${entry.value}`));
    } else if (entry.type === "delete") {
      console.log(pc.red(`- ${entry.value}`));
    } else {
      console.log(pc.dim(`  ${entry.value}`));
    }
  }
  console.log("");

  return true;
}